apiVersion: v1
kind: Service
metadata:
  name: multivac-web-server
  labels:
    app: multivac
    role: web-server
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: multivac
    role: web-server
