apiVersion: v1
kind: Service
metadata:
  name: multivac-redis
  labels:
    app: multivac
    role: cache
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: multivac
    role: cache
